// TODO
// Currently, the constants are exposed to webpack.config.js,
// so that it can inline replace the values in code at compile time.
// Also intellisense from TS highlights them as errors in code.
// Couldn't find a more elegant way to inline those :/

let i = 0;
export const constants = {
    OPERATOR_CREATOR: 0,
    OPERATOR_MODIFIER: 1,
    OPERATOR_QUERIER: 2,
    OPERATOR_CLEANER: 3,

    CONSTRAINT_TYPE_UNDEFINED: -1,
    CONSTRAINT_TYPE_FIXED: 0,
    CONSTRAINT_TYPE_POINT: 1,
    CONSTRAINT_TYPE_DISTANCE: 2,
    CONSTRAINT_TYPE_HINGE: 3,
    CONSTRAINT_TYPE_SLIDER: 4,
    CONSTRAINT_TYPE_CONE: 5,
    CONSTRAINT_TYPE_SWING_TWIST: 6,
    CONSTRAINT_TYPE_SIX_DOF: 7,
    CONSTRAINT_TYPE_PULLEY: 8,

    CONSTRAINT_SIX_DOF_TRANSLATION_X: 0,
    CONSTRAINT_SIX_DOF_TRANSLATION_Y: 1,
    CONSTRAINT_SIX_DOF_TRANSLATION_Z: 2,
    CONSTRAINT_SIX_DOF_ROTATION_X: 3,
    CONSTRAINT_SIX_DOF_ROTATION_Y: 4,
    CONSTRAINT_SIX_DOF_ROTATION_Z: 5,

    CONSTRAINT_SWING_TYPE_CONE: 0,
    CONSTRAINT_SWING_TYPE_PYRAMID: 1,

    CONSTRAINT_SPACE_LOCAL: 0,
    CONSTRAINT_SPACE_WORLD: 1,

    SPRING_MODE_FREQUENCY: 0,
    SPRING_MODE_STIFFNESS: 1,

    MOTOR_STATE_OFF: 0,
    MOTOR_STATE_VELOCITY: 1,
    MOTOR_STATE_POSITION: 2,

    VEHICLE_CAST_TYPE_RAY: 0,
    VEHICLE_CAST_TYPE_SPHERE: 1,
    VEHICLE_CAST_TYPE_CYLINDER: 2,

    OBJ_LAYER_NON_MOVING: 0,
    OBJ_LAYER_MOVING: 1,

    BP_LAYER_NON_MOVING: 0,
    BP_LAYER_MOVING: 1,

    SHAPE_BOX: 0,
    SHAPE_CAPSULE: 1,
    SHAPE_CYLINDER: 2,
    SHAPE_SPHERE: 3,
    SHAPE_MESH: 4,
    SHAPE_CONVEX_HULL: 5,
    SHAPE_STATIC_COMPOUND: 6,
    SHAPE_HEIGHTFIELD: 7,

    VEHICLE_TYPE_WHEEL: 0,
    VEHICLE_TYPE_TRACK: 1,
    VEHICLE_TYPE_MOTORCYCLE: 2,
    CONTACT_TYPE_ADDED: 0,
    CONTACT_TYPE_PERSISTED: 1,
    CONTACT_TYPE_REMOVED: 2,

    COMPONENT_SYSTEM_MANAGER: 0,
    COMPONENT_SYSTEM_BODY: 1,
    COMPONENT_SYSTEM_CHAR: 2,
    COMPONENT_SYSTEM_VEHICLE: 3,
    COMPONENT_SYSTEM_SOFT_BODY: 4,
    COMPONENT_SYSTEM_CONSTRAINT: 5,

    FLOAT32_SIZE: Float32Array.BYTES_PER_ELEMENT,
    INT32_SIZE: Int32Array.BYTES_PER_ELEMENT,
    UINT32_SIZE: Uint32Array.BYTES_PER_ELEMENT,
    UINT16_SIZE: Uint16Array.BYTES_PER_ELEMENT,
    UINT8_SIZE: Uint8Array.BYTES_PER_ELEMENT,

    BUFFER_WRITE_UINT8: JSON.stringify('writeUint8'),
    BUFFER_WRITE_UINT16: JSON.stringify('writeUint16'),
    BUFFER_WRITE_UINT32: JSON.stringify('writeUint32'),
    BUFFER_WRITE_INT32: JSON.stringify('writeInt32'),
    BUFFER_WRITE_VEC32: JSON.stringify('writeVector32'),
    BUFFER_WRITE_FLOAT32: JSON.stringify('writeFloat32'),
    BUFFER_WRITE_BOOL: JSON.stringify('writeBool'),
    BUFFER_WRITE_PLANE: JSON.stringify('writePlane'),
    BUFFER_WRITE_JOLTVEC32: JSON.stringify('writeJoltVec32'),
    BUFFER_READ_UINT8: JSON.stringify('readUint8'),
    BUFFER_READ_UINT16: JSON.stringify('readUint16'),
    BUFFER_READ_UINT32: JSON.stringify('readUint32'),
    BUFFER_READ_INT32: JSON.stringify('readInt32'),
    BUFFER_READ_FLOAT32: JSON.stringify('readFloat32'),
    BUFFER_READ_BOOL: JSON.stringify('readBool'),

    // frontend -> backend
    CMD_CREATE_BODY: i++,
    CMD_CREATE_CHAR: i++,
    CMD_CREATE_SHAPE: i++,
    CMD_CREATE_VEHICLE: i++,
    CMD_CREATE_SOFT_BODY: i++,
    CMD_ADD_FORCE: i++,
    CMD_ADD_IMPULSE: i++,
    CMD_APPLY_BUOYANCY_IMPULSE: i++,
    CMD_ADD_ANGULAR_IMPULSE: i++,
    CMD_ADD_TORQUE: i++,
    CMD_CAST_RAY: i++,
    CMD_CAST_SHAPE: i++,
    CMD_DESTROY_BODY: i++,
    CMD_DESTROY_SHAPE: i++,
    CMD_MOVE_BODY: i++,
    CMD_MOVE_KINEMATIC: i++,
    CMD_SET_LIN_VEL: i++,
    CMD_SET_ANG_VEL: i++,
    CMD_SET_MOTION_TYPE: i++,
    CMD_RESET_VELOCITIES: i++,
    CMD_TOGGLE_GROUP_PAIR: i++,
    CMD_CREATE_GROUPS: i++,
    CMD_CREATE_CONSTRAINT: i++,
    CMD_CHANGE_GRAVITY: i++,
    CMD_CHAR_SET_LIN_VEL: i++,
    CMD_CHAR_SET_SHAPE: i++,
    CMD_SET_USER_DATA: i++,
    CMD_USE_MOTION_STATE: i++,
    CMD_DESTROY_CONSTRAINT: i++,
    CMD_SET_DRIVER_INPUT: i++,
    CMD_PAIR_BODY: i++,
    
    // Joints 500-599

    CMD_JNT_SET_ENABLED: 509,

    CMD_JNT_ST_SET_N_H_C_ANGLE: 510,
    CMD_JNT_ST_SET_P_H_C_ANGLE: 511,
    CMD_JNT_ST_SET_T_MIN_ANGLE: 512,
    CMD_JNT_ST_SET_T_MAX_ANGLE: 513,
    CMD_JNT_ST_SET_M_F_TORQUE: 514,
    CMD_JNT_ST_SET_SWING_M_S: 515,
    CMD_JNT_ST_SET_TWIST_M_S: 516,
    CMD_JNT_ST_SET_T_ANG_VEL_CS: 517,

    CMD_JNT_D_SET_DISTANCE: 520,
    CMD_JNT_D_SET_SPRING_S: 521,

    CMD_JNT_H_SET_SPRING_S: 530,
    CMD_JNT_H_SET_M_F_TORQUE: 531,
    CMD_JNT_H_SET_M_S: 532,
    CMD_JNT_H_SET_T_ANG_VEL: 533,
    CMD_JNT_H_SET_T_ANGLE: 534,
    CMD_JNT_H_SET_LIMITS: 535,

    CMD_JNT_ST_SET_T_O_BS: 540,
    CMD_JNT_ST_SET_T_O_CS: 541,

    CMD_JNT_S_SET_M_F_FORCE: 550,
    CMD_JNT_S_SET_M_STATE: 551,
    CMD_JNT_S_SET_T_VEL: 552,
    CMD_JNT_S_SET_T_POS: 553,
    CMD_JNT_S_SET_LIMITS: 554,
    CMD_JNT_S_SET_SPRING_S: 555,

    CMD_JNT_C_SET_H_C_ANGLE: 560,

    CMD_JNT_SDF_SET_T_LIMITS: 570,
    CMD_JNT_SDF_SET_R_LIMITS: 571,
    CMD_JNT_SDF_SET_SPRING_S: 572,
    CMD_JNT_SDF_SET_M_F: 573,
    CMD_JNT_SDF_SET_M_STATE: 574,
    CMD_JNT_SDF_SET_T_VEL_CS: 575,
    CMD_JNT_SDF_SET_T_ANG_VEL_CS: 576,
    CMD_JNT_SDF_SET_T_POS_CS: 577,
    CMD_JNT_SDF_SET_T_ROT_CS: 578,
    CMD_JNT_SDF_SET_T_ROT_BS: 579,

    // backend -> frontend
    CMD_REPORT_TRANSFORMS: i++,
    CMD_REPORT_CONTACTS: i++,
    CMD_REPORT_SET_SHAPE: i++,
};