name: Publish to GPR

on:
  push:
    tags-ignore:
      '*-dev'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      
      - name: Install dependencies
        run: npm install

      - name: Build Physics
        run: npm run build

      - name: Publish to GitHub Packages Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}