name: Publish to GPR

on:
  push:
    branches: [ master ]

jobs:
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      
      - name: Install dependencies
        run: npm install

      - name: Publish to GitHub Packages Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}